function plotBBsurface(zdata1, xdata1, ydata1)
%CREATEFIGURE(zdata1, xdata1, ydata1)
%  ZDATA1:  surface zdata
%  XDATA1:  contour x
%  YDATA1:  contour y

%  Auto-generated by MATLAB on 02-Nov-2019 12:11:50

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create surf
surf(zdata1,'Parent',axes1);

% Create contour
contour(xdata1,ydata1,zdata1);

% Create zlabel
zlabel({'Estimated SPL (dB re 1 \muPa / Hz)'});

% Create ylabel
ylabel({'Hydrophone (AAA2)'});

% Create xlabel
xlabel({'Time Vector'});

% Create title
title({'Estimated broadband SPL for Ocean Endeavour'});

view(axes1,[-37.5 30]);
grid(axes1,'on');
axis(axes1,'tight');
% Create colorbar
colorbar(axes1);

