%% Import data from text file.
% Script for importing data from the following text file:
%
%    D:\NW2015FinalFieldTrial\BluRay\Data\BIRDSEYE metFiles Texas Weather Systems\MET_2015-09-05-00.dat
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/11/02 16:38:38

%% Initialize variables.
% filename = 'D:\NW2015FinalFieldTrial\BluRay\Data\BIRDSEYE metFiles Texas Weather Systems\MET_2015-09-05-01.dat';

%% Format for each line of text:
%   column2: datetimes (%{dd/MM/yy HH:mm:ss}D)
%	column3: double (%f)
%   column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*14s%17{yy/MM/dd HH:mm:ss}D%4f%6f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
winds = table(dataArray{1:end-1}, 'VariableNames', {'datetime','WD','MPH'});

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% MET2015090500.datetime=datenum(MET2015090500.datetime);

%% Clear temporary variables
clearvars filename formatSpec fileID dataArray ans;